# Generated by Django 4.2.13 on 2024-06-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Media_App', '0002_alter_customuser_mobile_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(null=True, upload_to='Pictures'),
        ),
    ]
