# Generated by Django 4.2.11 on 2024-06-21 06:11

import Social_Media_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Media_App', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Pictures', validators=[Social_Media_App.models.validated_file]),
        ),
    ]
